/**
 * Generates model/ASSUMPTIONS.md from INPUT_META, BASE_INPUTS, and the tornado ranking.
 * Invoked by cli.ts so the register always matches the code.
 */
import { BASE_INPUTS, TORNADO_CANDIDATES, computeTornado, type ModelInputs } from './fairr-model.ts';
import { INPUT_GROUPS, INPUT_META } from './input-meta.ts';

export function sensitivityRanks(inputs: ModelInputs = BASE_INPUTS): Map<keyof ModelInputs, number> {
  const t = computeTornado(inputs, TORNADO_CANDIDATES.length);
  const ranks = new Map<keyof ModelInputs, number>();
  t.bars.forEach((b, i) => {
    const cand = TORNADO_CANDIDATES.find((c) => c.key === b.key);
    for (const k of cand?.group ?? [b.key]) ranks.set(k, i + 1);
  });
  return ranks;
}

function fmt(v: number, format: string): string {
  if (format === 'pct') return `${(v * 100).toFixed(v * 100 % 1 === 0 ? 0 : 1)}%`;
  if (format === 'money') return `$${v.toLocaleString('en-US')}`;
  return String(v);
}

export function assumptionsMarkdown(inputs: ModelInputs = BASE_INPUTS): string {
  const ranks = sensitivityRanks(inputs);
  const lines: string[] = [];
  lines.push('# Model Assumptions Register');
  lines.push('');
  lines.push('Generated by `npm run model` from `model/input-meta.ts`. Every input is editable in the web app (`/model`), the Excel workbook (Inputs sheet), and `model/fairr-model.ts` (`BASE_INPUTS`).');
  lines.push('');
  lines.push('**Basis** cites `research/SOURCES.md` where a source exists. Inputs the sources do not support are marked `ASSUMPTION`. **Sensitivity rank** is the input\'s position in the tornado analysis on EBITDA Year 2 (1 = largest swing); a dash means the input was not among the tested candidates.');
  lines.push('');
  const keys = Object.keys(inputs) as Array<keyof ModelInputs>;
  const assumptionCount = keys.filter((k) => INPUT_META[k].assumption).length;
  lines.push(`Inputs: ${keys.length}. Labeled ASSUMPTION: ${assumptionCount}.`);
  lines.push('');
  for (const group of INPUT_GROUPS) {
    lines.push(`## ${group}`);
    lines.push('');
    lines.push('| Input | Key | Default | Unit | Basis | Sensitivity rank |');
    lines.push('|---|---|---|---|---|---|');
    for (const k of keys.filter((k) => INPUT_META[k].group === group)) {
      const m = INPUT_META[k];
      const rank = ranks.get(k);
      lines.push(`| ${m.label} | \`${k}\` | ${fmt(inputs[k], m.format)} | ${m.unit} | ${m.assumption ? '`ASSUMPTION` ' : ''}${m.basis.replace(/^ASSUMPTION: /, '')} | ${rank ?? '—'} |`);
    }
    lines.push('');
  }
  lines.push('## Structural assumptions (not single inputs)');
  lines.push('');
  lines.push('- Fixed-fee revenue is recognized ratably on delivered effort: the Assessment inside its month, the Sprint two-thirds in its first month and one-third in its second, retainers monthly, the Board Readout in its delivery month. See `docs/DECISIONS.md` #12.');
  lines.push('- The Sprint starts the month after the Assessment closes; the Retainer starts the month after the Sprint ends; renewals occur twelve months after each retainer start at the renewal rate.');
  lines.push('- Signed work beyond capacity queues as backlog; new assessments are declined while the backlog exceeds the cap, and their expected 36-month value is reported as revenue left on the table (`docs/DECISIONS.md` #10).');
  lines.push('- The Falcon Complete add-on is delivered mainly by the existing Falcon Complete and Threat Management teams; advisors contribute oversight hours that take first call on capacity, and a delivery-cost transfer is charged against add-on revenue (`docs/DECISIONS.md` #5).');
  lines.push('- The annual price escalator applies to all billings by practice year (`docs/DECISIONS.md` #13).');
  lines.push('- Net-45 payment terms collect half of each month\'s revenue in the following month and half in the month after (`docs/DECISIONS.md` #14).');
  lines.push('- The Falcon Flex program margin reduces net revenue on the Flex-transacted share of deals; CrowdStrike has not published partner economics (`docs/DECISIONS.md` #6).');
  lines.push('');
  return lines.join('\n');
}
